import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Слушать радио</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js, {data.name}!</a>
        </h1>
        <Link href={'/'}><a><Image src="/cautious-fm.svg" alt="Radio Logo" width={90} height={90} /></a></Link>
      </main>

    </div>
  )
}

export async function getServerSideProps(context) {
  const res = await fetch(`http://localhost:3000/api/hello`)
  const data = await res.json()

  return { props: { data } }
}
